### PR TITLE
Different file paths for Linux and Windows

### PR DESCRIPTION
**Pull request by gdavison**
If you're interested, I've made separate paths for Linux and Windows on top of your changes

### CODE REVIEW

**Comment by Ginja** [comment]
Thanks, @gdavison! What's the benefit of changing these paths though?

**Comment by gdavison** [comment]
The Linux Filesystem Hierarchy :)

It specifies where different types of files should live on Linux systems. For instance, the datastore should live under `/var/`, and most likely `/var/lib`. Config should go in `/etc`, but I could go either way on putting everything under `/etc/consul`
http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/

**Comment by Ginja** [comment]
Ha, of course. Normally I would agree, but for Consul I sort of like having everything under one roof. We should let @johnbellone weigh in on https://github.com/johnbellone/consul-cookbook/pull/259.

**Comment by gdavison** [comment]
Hmm, I was sure I had copied the `.conf`from somewhere, but I can't find it. No reason to make that different.

**Comment by Ginja** [comment]
Closing this in favour of [this](https://github.com/johnbellone/consul-cookbook/pull/259) being merged. Thanks though!

**Pull request closed without merging**
